### ISSUE TITLE
Market Activity Chart Not Displayed in Paper Trading Mode

### ISSUE THREAD

**Issue by pupplecat** [hummingbot/dashboard#102]
### Describe the bug

When using Hummingbot in paper trading mode (e.g., `binance_PaperTrade`), the Market Activity and Intraday Performance charts are not displayed in the Hummingbot Dashboard's Strategy Performance page.

### Steps to reproduce bug

1. Run Hummingbot with paper trade configuration (e.g., `binance_PaperTrade`).
2. Upload the Hummingbot SQLite Database file to the Strategy Performance page of the Dashboard.
3. Select a strategy for analysis.

### Observed Behavior

1. The exchange name displayed in the table is `binance` instead of `binance_PaperTrade`.
2. The Market Activity and Intraday Performance charts are blank.

**Comment by pupplecat** [comment]
### Potential Solutions for Discussion

**Option 1: Retain `_papertrade` in Market Name When Loading Data from Database**

- In the `database_manager`, the current logic replaces `_papertrade` with an empty string, causing `binance_PaperTrade` to be transformed into `binance`. The original purpose of this logic is unclear.
- This renaming results in a mismatch of the exchange name when filtering data for the Market Activity chart, which likely contributes to the issue at hand.
- I suspect this is the root cause of the problem. However, the overall impact of changing this logic to retain the `_papertrade` suffix in market names throughout the system is uncertain and needs further evaluation.

**Option 2: Remove `_papertrade` While Filtering Market Activity Data**

- Implement a similar approach as in Option 1 by removing the `_papertrade` suffix while applying the exchange/market filter in the `get_single_market_strategy_data` function.
- This change addresses the issue by ensuring the exchange/market name matches correctly for the Market Activity chart.  It's to note that this solution may not cover other similar cases.

**Comment by tomasgaudino** [comment]
### PR Available here: https://github.com/hummingbot/dashboard/pull/103

**_Option 1_** was the best solution since it doesn't introduce possible market missmatching in candlestick. Thanks to the given database, I could also found and fixed another potential bug. 

Thanks for taking this time!
