### ISSUE TITLE
Bug Report: click start，but doesn't work

### ISSUE THREAD

**Issue by jjwwon790626** [hummingbot/dashboard#136]
### Describe the bug

go through docs, step by step deploy dashboard,log in, click the start button, does not setup docker !
![36](https://github.com/hummingbot/dashboard/assets/88968632/c8a62855-370f-4c14-845c-b531b6cabf2f)

### Steps to reproduce bug

1. deploy dashbord
2.  register and log in 
3. click the start button

**Comment by jjwwon790626** [comment]
how to inspect the dashboard  running log?  what is the action of the click the start button?

**Comment by cardosofede** [comment]
@jjwwon790626 do you have docker running?

**Comment by rapcmia** [comment]
We recommend to use our new hummingbot 2.0, https://www.youtube.com/watch?v=kUCFhreCKKI
