### ISSUE TITLE
Portfolio: Price for some tokens on Kraken are 0

### ISSUE THREAD

**Issue by fengtality** [hummingbot/dashboard#194]
### Describe the bug

Portfolio balance for Kraken is wrong, because it's using 0 price for non-USDT tokens. However, other exchanges are computing price correctly for the same tokens.

### Steps to reproduce bug

Add Kraken credentials to Dashboard and observe portfolio. See ETH prices in OKX vs Kraken in the screenshot below:

<img width="814" alt="Screenshot 2024-11-07 at 7 11 22 AM" src="https://github.com/user-attachments/assets/aaadeb7a-dd3d-4a4c-82f5-724b94baef27">

**Comment by rapcmia** [comment]
Fixed on latest dashboard 
![image](https://github.com/user-attachments/assets/0a9738c3-0fe2-4729-ac58-35aa4ef4e5b2)
