### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by fengtality** [hummingbot/dashboard#38]
# Why

- Dashboard project README is out of date

# What

Update the Github README

- How to install / update
- How to set up
- How to run
- How to contribute
- How to join bi-weekly meetings

**Comment by cryptojorge** [comment]
We're talking about updating this page is my assumption
https://github.com/hummingbot/dashboard?ref=blog.hummingbot.org

**Comment by fengtality** [comment]
yes this is the README.md file in the repo
